/* ============================================================
 * SE 266 · Week 04 wiki: manifest + widget data
 * Loaded by dynamic injection from the shell. Articles are
 * markdown files in w04/articles/, fetched by the shell.
 * ============================================================ */
window.SE266_WIKI = {

  weekId: "w04",
  courseTitle: "SE 266 · Intro to Game Engines",
  weekTitle: "Week 04 · Design Vocabulary, What Makes Games Games",
  home: "home",

  /* sibling wikis at the content root, for [[peer:article|label]] links */
  peers: {
    res: "The Free Library.html",
    w01: "Week 01 - Engines, Anatomy, and Choosing Yours.html",
    w02: "Week 02 - Scene Graphs, Transforms, and Coordinate Spaces.html",
    w03: "Week 03 - The Game Loop, Time, and Input.html",
    w04: "Week 04 - Design Vocabulary, What Makes Games Games.html"
  },

  sections: [
    { name: "Start Here", articles: [
      { id: "home", title: "Week 4 Overview" }
    ]},
    { name: "Concepts", articles: [
      { id: "start-with-a-joke", title: "Start with a Joke" },
      { id: "core-loop", title: "The Core Loop" },
      { id: "mda", title: "MDA: Mechanics, Dynamics, Aesthetics" },
      { id: "player-promises", title: "Player Promises" },
      { id: "bartle", title: "Bartle's Taxonomy" },
      { id: "verbs-resources-feedback", title: "Verbs, Resources, Feedback Loops" },
      { id: "genre-tour", title: "The Genre Tour" },
      { id: "malicious-design", title: "Malicious Design" },
      { id: "scope", title: "Scope: Small, Finished, Polished" }
    ]},
    { name: "Supplemental", articles: [
      { id: "promise-grid", title: "The Promise Grid" }
    ]},
    { name: "Practice", articles: [
      { id: "playing-analytically", title: "How to Play Analytically" },
      { id: "the-workshop", title: "The Deconstruction Workshop" },
      { id: "tetris-deconstruction", title: "Worked Example: Tetris" },
      { id: "a12-template", title: "The Assignment 12 Template" }
    ]},
    { name: "This Week", articles: [
      { id: "this-weeks-work", title: "This Week's Work" }
    ]},
    { name: "Check Yourself", articles: [
      { id: "check-yourself", title: "Check Yourself" }
    ]}
  ],

  widgets: {

    quiz: [
      { q: "What is a core loop?",
        options: ["The main storyline of a game", "The small cycle of actions a player repeats for the whole runtime, usually 5 to 30 seconds", "The rendering loop the engine runs each frame", "The final boss encounter"],
        correct: 1,
        explain: "Every game has a small cycle the player runs thousands of times. If the loop is satisfying, the game survives a lot of other flaws; if it is dull, no cutscene or skill tree rescues it. It is the first sentence of any design doc." },
      { q: "In MDA, who owns which end?",
        options: ["The designer owns aesthetics; the player owns mechanics", "The designer writes mechanics (rules); the player experiences aesthetics (feelings); dynamics is the misty middle where they negotiate", "Mechanics and aesthetics are the same layer", "The engine owns all three"],
        correct: 1,
        explain: "The designer works at the mechanics end, the player lives at the aesthetics end, and neither can touch the other's layer directly. That is why playtesting is not optional: your head is not where the dynamics happen." },
      { q: "A playtester says the game 'feels grindy.' How does the MDA trace run?",
        options: ["Grindy is an aesthetic; ignore it, feelings aren't data", "Feeling (grindy) to behavior (repeating the same safe action because it pays too well) to rule (the gold reward is a number in a file you can change)", "Add more content until it stops feeling grindy", "Rewrite the story"],
        correct: 1,
        explain: "The fundamental move of game design runs backward: from the aesthetic complaint, to the dynamic causing it, to the mechanic underneath. Assignment 12 grades whether you can perform this trace on someone else's game." },
      { q: "What is a positive feedback loop?",
        options: ["A loop that makes players feel good", "When winning makes winning easier: it creates momentum, blowouts, and ends games", "When losing gives you help to catch up", "Any loop the player enjoys"],
        correct: 1,
        explain: "Positive loops (Monopoly's rich-get-richer, an RTS economy snowball) create momentum and end games. Negative loops (Mario Kart's blue shell, rubber-band AI) create comebacks and keep games close. Most balance complaints are feedback-loop complaints." },
      { q: "What is Tetris's central resource?",
        options: ["Points", "Board space: every placement spends it, every cleared line refunds it", "Lives", "The next piece"],
        correct: 1,
        explain: "Almost nobody names it on the first try. Tetris's real resource is board space, and you manage a shrinking budget the whole game. Resource analysis reveals structure that themes hide: follow the resources and you find the actual game under the art." },
      { q: "How many verbs does Tetris have, and what school of design does that put it in?",
        options: ["Fourteen; the many-loose school", "Four (shift, rotate, drop, hold); the few-verbs-deeply-explored school", "One; too simple to analyze", "Zero; it plays itself"],
        correct: 1,
        explain: "Count a game's verbs and you know its shape. A tight game has few verbs deeply explored; a sprawling game has many loosely explored. A design doc that lists fourteen verbs for a one-semester project has already failed." },
      { q: "Your dream game has fourteen verbs. What's the move?",
        options: ["Build all fourteen; ambition is good", "Design the smallest version that still produces the aesthetic you're chasing, and build that. Small, finished, and polished beats big and broken", "Cut it to exactly seven verbs", "Add a fifteenth so it feels complete"],
        correct: 1,
        explain: "Every student proposal is too big, all of them. If the tension comes from being chased in the dark, you need one dark hallway and one chaser, not a mansion. You can always add the mansion; nobody has subtracted one in finals week." },
      { q: "A game teaches you that stealth is the way, then forces a loud mandatory boss fight the player cannot avoid. Why does this read as 'unfair' even when the fight is winnable?",
        options: ["It isn't unfair; the player is just bad at combat", "It broke a player promise: the game taught one approach, then punished the player for using it. The unfairness traces back through the contradiction to the rule that broke the earlier rule", "Boss fights are always unfair", "The difficulty was set too high"],
        correct: 1,
        explain: "That 'this feels cheap' reaction is almost always a broken promise. Most of design from the player's side is promise management: know what you are promising, keep it, and do not promise what your scope cannot cash." },
      { q: "You pre-order a game you have never seen played, on the strength of the studio's name alone. What did you actually buy?",
        options: ["The game itself", "A promise, backed by the studio's whole back catalog as collateral: player promises start before you install, made by the studio, the franchise name, the trailer, and the tags on the store page", "Nothing; pre-orders are irrational", "A refund waiting to happen"],
        correct: 1,
        explain: "The contract begins before the title screen. Pre-purchase promises are also the easiest to break, because the studio makes them to sell and the game has to keep them to satisfy. A pitch deck is that whole layer, formalized: promises exciting enough to greenlight and honest enough to ship." },
      { q: "In Bartle's taxonomy, what are the two axes that define the four player types?",
        options: ["Casual vs. hardcore, and single vs. multiplayer", "Acting vs. interacting, and the world vs. other players: Achievers act on the world, Explorers interact with the world, Killers act on players, Socializers interact with players", "Skill vs. luck, and offense vs. defense", "Winning vs. losing, and fast vs. slow"],
        correct: 1,
        explain: "Achievers want completion, Explorers want to understand, Socializers want the people, Killers want to win against a human. It is a lens not a law, nobody is one type, and its real use is a design check: which types am I serving, and is that on purpose?" },
      { q: "A free-to-play game is generous for its first few hours, then hits you with a daily energy cap you can skip for $10. What is this, in the vocabulary of this week?",
        options: ["Good onboarding: it respects the player's time", "MDA weaponized: the same mechanics tuned to produce compulsion instead of fun, manufacturing a pain (the wall) so it can sell the cure (the chest)", "A negative feedback loop that keeps the game fair", "Just pay-to-win, which is harmless"],
        correct: 1,
        explain: "The onboarding generosity was a loan; the wall is the collection. The tell of malicious design is how the game answers 'how do I get out of this pressure': an honest game says get better, a malicious one says get out your card." },
      { q: "What separates an honest loop of doom (Tetris) from a malicious one (a gacha game)?",
        options: ["Nothing; both are just difficulty", "In Tetris every escape from the spiral is skill you earned; in the malicious version the escape is your wallet, and the 'skill' being sold is a payment method", "Tetris is harder", "The malicious one has better graphics"],
        correct: 1,
        explain: "Both run a loop of doom, but one is honest and one is not. The line for your own designs is consent: are you producing an experience the player would thank you for, or manufacturing a behavior they would switch off if the game let them?" },
      { q: "Why is 'malicious design' in a design-vocabulary week and not a rant blog?",
        options: ["To scare students away from making games", "Because you are about to learn to build these exact mechanics (feedback loops, variable rewards, progression gates); they work, that is the danger, and naming the patterns is how you choose to build for the player who would thank you", "It isn't; it should be removed", "Because all monetization is evil"],
        correct: 1,
        explain: "The knife that carves your dinner is the knife that could do the other thing. The line is not the mechanic, it is consent. A game designed around an aesthetic the player consents to does not need a wall, a clock, or a chest; it needs to be good, and then to end." },
      { q: "Why is the core loop 'load-bearing'?",
        options: ["It uses the most CPU", "The player runs it thousands of times, so if it is dull, nothing bolted on top rescues it", "It holds up the game's physics", "It determines the frame rate"],
        correct: 1,
        explain: "Tetris has no story, no characters, and no ending, and it outsold most things with all three, because its seven-second loop is satisfying. No open world is beautiful enough to save a boring seven seconds repeated four thousand times." }
    ],

    checklist: {
      items: [
        { id: "catchup", label: "Catch up: Assignment 1 and Assignment 2 submitted, or resubmitted if they came back", optional: false },
        { id: "workshop", label: "Attend or watch the deconstruction workshop (remote students: post your template plus two replies)", optional: false },
        { id: "analytical", label: "Run the analytical-play method on one game you're already playing anyway", optional: false },
        { id: "shortlist", label: "Shortlist two candidate games for Assignment 12 and write each core loop in one sentence", optional: false },
        { id: "mda-paper", label: "Read the MDA paper (five pages) before Assignment 12", optional: true }
      ],
      note: "A personal tracker only: this browser, not the gradebook. No new assignment is paced this week; it is a catch-up week for Assignment 1 and Assignment 2. Everything here is a dress rehearsal for Assignment 12, which you present in Week 15 on a game you choose."
    },

    promisegrid: {
      axes: [
        { id: "d", label: "What you do", cells: [
          { id: "fight",   label: "Fight" },
          { id: "command", label: "Command" },
          { id: "explore", label: "Explore" },
          { id: "solve",   label: "Solve" }
        ]},
        { id: "w", label: "Who with", cells: [
          { id: "solo",    label: "Solo" },
          { id: "coop",    label: "Co-op" },
          { id: "versus",  label: "Versus" },
          { id: "massive", label: "Massive" }
        ]},
        { id: "s", label: "How it is shaped", cells: [
          { id: "campaign",   label: "Campaign" },
          { id: "persistent", label: "Persistent" },
          { id: "runbased",   label: "Run-based" },
          { id: "match",      label: "Match" }
        ]},
        { id: "f", label: "How it feels", cells: [
          { id: "mastery", label: "Mastery" },
          { id: "cozy",    label: "Cozy" },
          { id: "tension", label: "Tension" },
          { id: "power",   label: "Power" }
        ]}
      ],
      games: [
        { n: "Elden Ring",                      d: "fight",   w: "solo",    s: "persistent", f: "mastery" },
        { n: "Dark Souls III",                  d: "fight",   w: "solo",    s: "persistent", f: "mastery" },
        { n: "Sekiro",                          d: "fight",   w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Bloodborne",                      d: "fight",   w: "solo",    s: "persistent", f: "mastery" },
        { n: "Hades",                           d: "fight",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Dead Cells",                      d: "fight",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Devil May Cry 5",                 d: "fight",   w: "solo",    s: "campaign",   f: "mastery" },
        { n: "God of War (2018)",               d: "fight",   w: "solo",    s: "campaign",   f: "power" },
        { n: "Doom (2016)",                     d: "fight",   w: "solo",    s: "campaign",   f: "power" },
        { n: "Vampire Survivors",               d: "fight",   w: "solo",    s: "runbased",   f: "power" },
        { n: "Path of Exile",                   d: "fight",   w: "solo",    s: "persistent", f: "power" },
        { n: "Resident Evil 4",                 d: "fight",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Cuphead",                         d: "fight",   w: "coop",    s: "campaign",   f: "mastery" },
        { n: "Diablo IV",                       d: "fight",   w: "coop",    s: "persistent", f: "power" },
        { n: "Destiny 2",                       d: "fight",   w: "coop",    s: "persistent", f: "power" },
        { n: "Borderlands 3",                   d: "fight",   w: "coop",    s: "campaign",   f: "power" },
        { n: "Left 4 Dead 2",                   d: "fight",   w: "coop",    s: "match",      f: "tension" },
        { n: "Counter-Strike 2",                d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Valorant",                        d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Overwatch 2",                     d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Rainbow Six Siege",               d: "fight",   w: "versus",  s: "match",      f: "tension" },
        { n: "Team Fortress 2",                 d: "fight",   w: "versus",  s: "match",      f: "power" },
        { n: "Halo Infinite",                   d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Street Fighter 6",                d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Super Smash Bros. Ultimate",      d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Tekken 8",                        d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Rocket League",                   d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Dead by Daylight",                d: "fight",   w: "versus",  s: "match",      f: "tension" },
        { n: "Mario Kart 8 Deluxe",             d: "fight",   w: "versus",  s: "match",      f: "power" },
        { n: "Call of Duty: Warzone",           d: "fight",   w: "massive", s: "match",      f: "tension" },
        { n: "Fortnite",                        d: "fight",   w: "massive", s: "match",      f: "tension" },
        { n: "Apex Legends",                    d: "fight",   w: "massive", s: "match",      f: "tension" },
        { n: "PUBG: Battlegrounds",             d: "fight",   w: "massive", s: "match",      f: "tension" },
        { n: "Escape from Tarkov",              d: "fight",   w: "massive", s: "match",      f: "tension" },
        { n: "StarCraft II",                    d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "Age of Empires IV",               d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "Clash Royale",                    d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "EA Sports FC 24",                 d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "Civilization VI",                 d: "command", w: "solo",    s: "match",      f: "mastery" },
        { n: "Into the Breach",                 d: "command", w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Slay the Spire",                  d: "command", w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Balatro",                         d: "command", w: "solo",    s: "runbased",   f: "power" },
        { n: "XCOM 2",                          d: "command", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Fire Emblem: Three Houses",       d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Total War: Warhammer III",        d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Frostpunk",                       d: "command", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Bloons TD 6",                     d: "command", w: "solo",    s: "match",      f: "tension" },
        { n: "Plants vs. Zombies",              d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Cities: Skylines",                d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Stardew Valley",                  d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Animal Crossing: New Horizons",   d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "The Sims 4",                      d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Two Point Hospital",              d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Football Manager 2024",           d: "command", w: "solo",    s: "persistent", f: "mastery" },
        { n: "RimWorld",                        d: "command", w: "solo",    s: "persistent", f: "tension" },
        { n: "Oxygen Not Included",             d: "command", w: "solo",    s: "persistent", f: "tension" },
        { n: "Crusader Kings III",              d: "command", w: "solo",    s: "persistent", f: "tension" },
        { n: "Factorio",                        d: "command", w: "coop",    s: "persistent", f: "mastery" },
        { n: "Don't Starve Together",           d: "command", w: "coop",    s: "runbased",   f: "tension" },
        { n: "The Witcher 3",                   d: "explore", w: "solo",    s: "persistent", f: "power" },
        { n: "Skyrim",                          d: "explore", w: "solo",    s: "persistent", f: "power" },
        { n: "The Legend of Zelda: BOTW",       d: "explore", w: "solo",    s: "persistent", f: "power" },
        { n: "Tears of the Kingdom",            d: "explore", w: "solo",    s: "persistent", f: "power" },
        { n: "Red Dead Redemption 2",           d: "explore", w: "solo",    s: "persistent", f: "tension" },
        { n: "Cyberpunk 2077",                  d: "explore", w: "solo",    s: "persistent", f: "power" },
        { n: "Mass Effect 2",                   d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Disco Elysium",                   d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Hollow Knight",                   d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Metroid Dread",                   d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Celeste",                         d: "explore", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Super Mario Odyssey",             d: "explore", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Ori and the Will of the Wisps",   d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Outer Wilds",                     d: "explore", w: "solo",    s: "persistent", f: "tension" },
        { n: "Subnautica",                      d: "explore", w: "solo",    s: "persistent", f: "tension" },
        { n: "A Short Hike",                    d: "explore", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Firewatch",                       d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Untitled Goose Game",             d: "explore", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Amnesia: The Dark Descent",       d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Baldur's Gate 3",                 d: "explore", w: "coop",    s: "campaign",   f: "mastery" },
        { n: "It Takes Two",                    d: "explore", w: "coop",    s: "campaign",   f: "power" },
        { n: "Journey",                         d: "explore", w: "coop",    s: "campaign",   f: "cozy" },
        { n: "Terraria",                        d: "explore", w: "coop",    s: "persistent", f: "power" },
        { n: "Minecraft",                       d: "explore", w: "coop",    s: "persistent", f: "cozy" },
        { n: "No Man's Sky",                    d: "explore", w: "coop",    s: "persistent", f: "cozy" },
        { n: "Valheim",                         d: "explore", w: "coop",    s: "persistent", f: "tension" },
        { n: "Genshin Impact",                  d: "explore", w: "coop",    s: "persistent", f: "power" },
        { n: "Phasmophobia",                    d: "explore", w: "coop",    s: "match",      f: "tension" },
        { n: "World of Warcraft",               d: "explore", w: "massive", s: "persistent", f: "power" },
        { n: "Final Fantasy XIV",               d: "explore", w: "massive", s: "persistent", f: "power" },
        { n: "Old School RuneScape",            d: "explore", w: "massive", s: "persistent", f: "cozy" },
        { n: "Sea of Thieves",                  d: "explore", w: "massive", s: "persistent", f: "cozy" },
        { n: "Fall Guys",                       d: "explore", w: "massive", s: "match",      f: "cozy" },
        { n: "Tetris",                          d: "solve",   w: "solo",    s: "match",      f: "mastery" },
        { n: "The Witness",                     d: "solve",   w: "solo",    s: "persistent", f: "mastery" },
        { n: "Baba Is You",                     d: "solve",   w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Return of the Obra Dinn",         d: "solve",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Inscryption",                     d: "solve",   w: "solo",    s: "runbased",   f: "tension" },
        { n: "Dorfromantik",                    d: "solve",   w: "solo",    s: "runbased",   f: "cozy" },
        { n: "Mini Metro",                      d: "solve",   w: "solo",    s: "match",      f: "cozy" },
        { n: "Wordle",                          d: "solve",   w: "solo",    s: "match",      f: "cozy" },
        { n: "2048",                            d: "solve",   w: "solo",    s: "match",      f: "cozy" },
        { n: "Candy Crush Saga",                d: "solve",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Unpacking",                       d: "solve",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Portal 2",                        d: "solve",   w: "coop",    s: "campaign",   f: "mastery" },
        { n: "Human: Fall Flat",                d: "solve",   w: "coop",    s: "campaign",   f: "cozy" },
        { n: "Powerwash Simulator",             d: "solve",   w: "coop",    s: "campaign",   f: "cozy" },
        { n: "Among Us",                        d: "solve",   w: "versus",  s: "match",      f: "tension" },
        { n: "Jackbox Party Pack",              d: "solve",   w: "versus",  s: "match",      f: "cozy" },
        { n: "Tetris 99",                       d: "solve",   w: "massive", s: "match",      f: "tension" },

        /* --- Canon and retro (pre-2000) --- */
        { n: "Super Mario Bros. 3",             d: "explore", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Super Mario World",               d: "explore", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "The Legend of Zelda: OOT",        d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Super Metroid",                   d: "explore", w: "solo",    s: "persistent", f: "tension" },
        { n: "Chrono Trigger",                  d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Final Fantasy VII",               d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Doom (1993)",                     d: "fight",   w: "solo",    s: "campaign",   f: "power" },
        { n: "Street Fighter II",               d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Pac-Man",                         d: "solve",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Space Invaders",                  d: "fight",   w: "solo",    s: "runbased",   f: "tension" },
        { n: "Donkey Kong (1981)",              d: "explore", w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Mega Man 2",                      d: "fight",   w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Castlevania: SOTN",               d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Secret of Mana",                  d: "fight",   w: "coop",    s: "campaign",   f: "power" },
        { n: "GoldenEye 007",                   d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Diablo II",                       d: "fight",   w: "solo",    s: "persistent", f: "power" },
        { n: "Half-Life",                       d: "fight",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Quake III Arena",                 d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Command & Conquer",               d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "Warcraft III",                    d: "command", w: "versus",  s: "match",      f: "power" },
        { n: "SimCity 2000",                    d: "command", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Myst",                            d: "solve",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Age of Empires II",               d: "command", w: "versus",  s: "match",      f: "mastery" },

        /* --- Nintendo and family --- */
        { n: "Mario Party Superstars",          d: "solve",   w: "versus",  s: "match",      f: "cozy" },
        { n: "Kirby and the Forgotten Land",    d: "fight",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Kirby's Return to Dream Land",    d: "fight",   w: "coop",    s: "campaign",   f: "cozy" },
        { n: "Pokemon Scarlet & Violet",        d: "fight",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Pokemon Legends: Arceus",         d: "explore", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Luigi's Mansion 3",               d: "solve",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Yoshi's Crafted World",           d: "explore", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Splatoon 3",                      d: "fight",   w: "versus",  s: "match",      f: "power" },
        { n: "Donkey Kong Country: Tropical",   d: "explore", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Mario Kart 64",                   d: "fight",   w: "versus",  s: "match",      f: "cozy" },
        { n: "Mario Golf: Super Rush",          d: "command", w: "versus",  s: "match",      f: "cozy" },
        { n: "Super Smash Bros. Melee",         d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Fire Emblem: Awakening",          d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Xenoblade Chronicles 3",          d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Pikmin 4",                        d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Ring Fit Adventure",              d: "fight",   w: "solo",    s: "persistent", f: "mastery" },
        { n: "Slime Rancher",                   d: "fight",   w: "solo",    s: "persistent", f: "cozy" },

        /* --- JRPG --- */
        { n: "Final Fantasy X",                 d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Persona 5 Royal",                 d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Persona 4 Golden",                d: "explore", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Dragon Quest XI",                 d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Xenoblade Chronicles 2",          d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Octopath Traveler II",            d: "explore", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Fire Emblem Engage",              d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Tales of Arise",                  d: "fight",   w: "solo",    s: "campaign",   f: "power" },
        { n: "NieR: Automata",                  d: "fight",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Ni no Kuni II",                   d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Bravely Default II",              d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Monster Hunter: World",           d: "fight",   w: "coop",    s: "runbased",   f: "mastery" },
        { n: "Monster Hunter Rise",             d: "fight",   w: "coop",    s: "runbased",   f: "mastery" },
        { n: "Granblue Fantasy: Relink",        d: "fight",   w: "coop",    s: "campaign",   f: "power" },
        { n: "Trials of Mana",                  d: "fight",   w: "coop",    s: "campaign",   f: "mastery" },
        { n: "Fantasian Neo Dimension",         d: "explore", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Ys VIII: Lacrimosa of Dana",      d: "fight",   w: "solo",    s: "campaign",   f: "power" },
        { n: "Dragon Ball Z: Kakarot",          d: "fight",   w: "solo",    s: "campaign",   f: "power" },

        /* --- Modern shooters --- */
        { n: "Doom Eternal",                    d: "fight",   w: "solo",    s: "campaign",   f: "power" },
        { n: "Titanfall 2",                     d: "fight",   w: "solo",    s: "campaign",   f: "power" },
        { n: "Half-Life 2",                     d: "fight",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Half-Life: Alyx",                 d: "fight",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Portal (2007)",                   d: "solve",   w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Metro Exodus",                    d: "fight",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Battlefield 2042",                d: "fight",   w: "massive", s: "match",      f: "tension" },
        { n: "Modern Warfare II",               d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Splitgate",                       d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "The Finals",                      d: "fight",   w: "versus",  s: "match",      f: "power" },
        { n: "Gears 5",                         d: "fight",   w: "coop",    s: "campaign",   f: "power" },
        { n: "Helldivers 2",                    d: "fight",   w: "coop",    s: "persistent", f: "tension" },
        { n: "Deep Rock Galactic",              d: "fight",   w: "coop",    s: "runbased",   f: "cozy" },
        { n: "Payday 3",                        d: "fight",   w: "coop",    s: "runbased",   f: "tension" },
        { n: "Warframe",                        d: "fight",   w: "coop",    s: "persistent", f: "power" },
        { n: "Planetside 2",                    d: "fight",   w: "massive", s: "persistent", f: "mastery" },
        { n: "Naraka: Bladepoint",              d: "fight",   w: "massive", s: "match",      f: "tension" },
        { n: "Hunt: Showdown",                  d: "fight",   w: "versus",  s: "match",      f: "tension" },
        { n: "Squad",                           d: "fight",   w: "massive", s: "match",      f: "tension" },
        { n: "Insurgency: Sandstorm",           d: "fight",   w: "versus",  s: "match",      f: "tension" },

        /* --- Strategy, 4X, tactics --- */
        { n: "Civilization V",                  d: "command", w: "solo",    s: "match",      f: "mastery" },
        { n: "Humankind",                       d: "command", w: "solo",    s: "match",      f: "mastery" },
        { n: "Stellaris",                       d: "command", w: "solo",    s: "persistent", f: "power" },
        { n: "Europa Universalis IV",           d: "command", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Hearts of Iron IV",               d: "command", w: "solo",    s: "persistent", f: "tension" },
        { n: "Company of Heroes 3",             d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "Warhammer 40,000: Darktide",      d: "fight",   w: "coop",    s: "runbased",   f: "tension" },
        { n: "Total War: Rome II",              d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Advance Wars: Re-Boot Camp",      d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Battle Brothers",                 d: "command", w: "solo",    s: "persistent", f: "tension" },
        { n: "Mount & Blade II: Bannerlord",    d: "fight",   w: "solo",    s: "persistent", f: "power" },
        { n: "Homeworld 3",                     d: "command", w: "solo",    s: "campaign",   f: "power" },
        { n: "Teamfight Tactics",               d: "command", w: "versus",  s: "runbased",   f: "mastery" },
        { n: "Auto Chess",                      d: "command", w: "versus",  s: "runbased",   f: "mastery" },
        { n: "Northgard",                       d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "They Are Billions",               d: "command", w: "solo",    s: "runbased",   f: "tension" },
        { n: "Anno 1800",                       d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Frostpunk 2",                     d: "command", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Wargroove",                       d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Age of Mythology: Retold",        d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "Total War: Three Kingdoms",       d: "command", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Endless Space 2",                 d: "command", w: "solo",    s: "persistent", f: "power" },
        { n: "Griftlands",                      d: "command", w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Marvel Snap",                     d: "command", w: "versus",  s: "match",      f: "mastery" },

        /* --- Sim, management, cozy --- */
        { n: "Planet Coaster 2",                d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Two Point Museum",                d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "House Flipper 2",                 d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Farming Simulator 25",            d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "My Time at Sandrock",             d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Coral Island",                    d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Ooblets",                         d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Fields of Mistria",               d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Disney Dreamlight Valley",        d: "command", w: "coop",    s: "persistent", f: "cozy" },
        { n: "Viva Pinata",                     d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Planet Zoo",                      d: "command", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Prison Architect",                d: "command", w: "solo",    s: "persistent", f: "tension" },
        { n: "Two Point Campus",                d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Game Dev Tycoon",                 d: "command", w: "solo",    s: "persistent", f: "mastery" },
        { n: "RollerCoaster Tycoon 2",          d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "SimCity 4",                       d: "command", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Banished",                        d: "command", w: "solo",    s: "persistent", f: "tension" },
        { n: "Dwarf Fortress",                  d: "command", w: "solo",    s: "persistent", f: "tension" },
        { n: "Kynseed",                         d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Spiritfarer",                     d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Cozy Grove",                      d: "explore", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Wylde Flowers",                   d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Potion Craft",                    d: "solve",   w: "solo",    s: "persistent", f: "cozy" },
        { n: "Bear and Breakfast",              d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Coffee Talk",                     d: "explore", w: "solo",    s: "campaign",   f: "cozy" },

        /* --- Metroidvania and platformer --- */
        { n: "Blasphemous 2",                   d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Guacamelee! 2",                   d: "explore", w: "coop",    s: "persistent", f: "mastery" },
        { n: "Axiom Verge",                     d: "explore", w: "solo",    s: "persistent", f: "tension" },
        { n: "Prince of Persia: Lost Crown",    d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Grime",                           d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Rain World",                      d: "explore", w: "solo",    s: "persistent", f: "tension" },
        { n: "Cave Story",                      d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Shovel Knight",                   d: "explore", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Super Meat Boy",                  d: "explore", w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Hades II",                        d: "fight",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Katana ZERO",                     d: "fight",   w: "solo",    s: "campaign",   f: "mastery" },
        { n: "Inside",                          d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Limbo",                           d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "A Hat in Time",                   d: "explore", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Psychonauts 2",                   d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Ratchet & Clank: Rift Apart",     d: "fight",   w: "solo",    s: "campaign",   f: "power" },
        { n: "Sackboy: A Big Adventure",        d: "explore", w: "coop",    s: "campaign",   f: "cozy" },

        /* --- Horror --- */
        { n: "Silent Hill 2",                   d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Outlast",                         d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Alien: Isolation",                d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Dead Space (2023)",               d: "fight",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "The Evil Within",                 d: "fight",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Little Nightmares II",            d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Five Nights at Freddy's",         d: "solve",   w: "solo",    s: "runbased",   f: "tension" },
        { n: "Until Dawn",                      d: "solve",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Lethal Company",                  d: "fight",   w: "coop",    s: "runbased",   f: "tension" },
        { n: "Content Warning",                 d: "explore", w: "coop",    s: "runbased",   f: "tension" },
        { n: "Fatal Frame: Black Water",        d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "The Quarry",                      d: "solve",   w: "coop",    s: "campaign",   f: "tension" },
        { n: "Devour",                          d: "fight",   w: "coop",    s: "runbased",   f: "tension" },
        { n: "Poppy Playtime",                  d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Resident Evil Village",           d: "fight",   w: "solo",    s: "campaign",   f: "tension" },

        /* --- Puzzle, word, casual, mobile --- */
        { n: "Monument Valley",                 d: "solve",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Threes!",                         d: "solve",   w: "solo",    s: "match",      f: "cozy" },
        { n: "Angry Birds",                     d: "solve",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Cut the Rope",                    d: "solve",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Fruit Ninja",                     d: "solve",   w: "solo",    s: "match",      f: "cozy" },
        { n: "NYT Connections",                 d: "solve",   w: "solo",    s: "match",      f: "cozy" },
        { n: "NYT Spelling Bee",                d: "solve",   w: "solo",    s: "match",      f: "cozy" },
        { n: "Sudoku",                          d: "solve",   w: "solo",    s: "persistent", f: "cozy" },
        { n: "Words With Friends",              d: "solve",   w: "versus",  s: "match",      f: "cozy" },
        { n: "Wordscapes",                      d: "solve",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Tetris Effect: Connected",        d: "solve",   w: "coop",    s: "match",      f: "power" },
        { n: "Puyo Puyo Tetris 2",              d: "solve",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Bejeweled 3",                     d: "solve",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Peggle",                          d: "solve",   w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Cooking Mama",                    d: "command", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Overcooked! 2",                   d: "command", w: "coop",    s: "match",      f: "tension" },
        { n: "Stack",                           d: "solve",   w: "solo",    s: "runbased",   f: "cozy" },
        { n: "Flappy Bird",                     d: "solve",   w: "solo",    s: "runbased",   f: "tension" },
        { n: "Geometry Dash",                   d: "solve",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Suika Game",                      d: "solve",   w: "solo",    s: "persistent", f: "cozy" },
        { n: "Papers, Please",                  d: "solve",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Her Story",                       d: "solve",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Loop Hero",                       d: "solve",   w: "solo",    s: "runbased",   f: "tension" },

        /* --- MMO and persistent online --- */
        { n: "EVE Online",                      d: "command", w: "massive", s: "persistent", f: "power" },
        { n: "Foxhole",                         d: "command", w: "massive", s: "persistent", f: "tension" },
        { n: "Realm of the Mad God",            d: "fight",   w: "massive", s: "runbased",   f: "tension" },
        { n: "Guild Wars 2",                    d: "explore", w: "massive", s: "persistent", f: "power" },
        { n: "Black Desert Online",             d: "fight",   w: "massive", s: "persistent", f: "power" },
        { n: "Lost Ark",                        d: "fight",   w: "massive", s: "persistent", f: "power" },
        { n: "Star Wars: The Old Republic",     d: "explore", w: "massive", s: "persistent", f: "power" },
        { n: "New World: Aeternum",             d: "fight",   w: "massive", s: "persistent", f: "tension" },
        { n: "Elder Scrolls Online",            d: "explore", w: "massive", s: "persistent", f: "power" },
        { n: "Path of Exile 2",                 d: "fight",   w: "solo",    s: "persistent", f: "power" },
        { n: "Diablo III",                      d: "fight",   w: "coop",    s: "persistent", f: "power" },
        { n: "Second Life",                     d: "explore", w: "massive", s: "persistent", f: "cozy" },
        { n: "Club Penguin",                    d: "explore", w: "massive", s: "persistent", f: "cozy" },
        { n: "Toontown Rewritten",              d: "fight",   w: "massive", s: "persistent", f: "cozy" },
        { n: "Neopets",                         d: "command", w: "massive", s: "persistent", f: "cozy" },
        { n: "Fallout 76",                      d: "fight",   w: "massive", s: "persistent", f: "tension" },
        { n: "Conan Exiles",                    d: "fight",   w: "massive", s: "persistent", f: "tension" },
        { n: "ARK: Survival Ascended",          d: "explore", w: "massive", s: "persistent", f: "tension" },

        /* --- Fighting, sports, racing --- */
        { n: "Mortal Kombat 1",                 d: "fight",   w: "versus",  s: "match",      f: "power" },
        { n: "Guilty Gear Strive",              d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Granblue Fantasy Versus Rising",  d: "fight",   w: "versus",  s: "match",      f: "mastery" },
        { n: "Dragon Ball FighterZ",            d: "fight",   w: "versus",  s: "match",      f: "power" },
        { n: "NBA 2K25",                        d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "MLB The Show 24",                 d: "command", w: "versus",  s: "match",      f: "mastery" },
        { n: "WWE 2K24",                        d: "fight",   w: "versus",  s: "match",      f: "power" },
        { n: "Tony Hawk's Pro Skater 1+2",      d: "explore", w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Golf With Your Friends",          d: "command", w: "versus",  s: "match",      f: "cozy" },
        { n: "Forza Horizon 5",                 d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Gran Turismo 7",                  d: "explore", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Mario Kart Wii",                  d: "fight",   w: "versus",  s: "match",      f: "cozy" },
        { n: "Trackmania",                      d: "explore", w: "versus",  s: "match",      f: "mastery" },
        { n: "F1 24",                           d: "explore", w: "versus",  s: "match",      f: "mastery" },
        { n: "Wreckfest",                       d: "fight",   w: "versus",  s: "match",      f: "power" },
        { n: "Need for Speed Unbound",          d: "explore", w: "versus",  s: "match",      f: "power" },
        { n: "Burnout Paradise Remastered",     d: "explore", w: "solo",    s: "persistent", f: "power" },
        { n: "iRacing",                         d: "explore", w: "versus",  s: "match",      f: "mastery" },
        { n: "Descenders",                      d: "explore", w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Motorsport Manager",              d: "command", w: "solo",    s: "persistent", f: "mastery" },
        { n: "Hot Wheels Unleashed",            d: "explore", w: "versus",  s: "match",      f: "cozy" },

        /* --- Narrative and adventure --- */
        { n: "What Remains of Edith Finch",     d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Life is Strange",                 d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Detroit: Become Human",           d: "solve",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Oxenfree",                        d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Gone Home",                       d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "The Stanley Parable",             d: "explore", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "Kentucky Route Zero",             d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "80 Days",                         d: "solve",   w: "solo",    s: "persistent", f: "mastery" },
        { n: "Night in the Woods",              d: "explore", w: "solo",    s: "campaign",   f: "cozy" },
        { n: "A Plague Tale: Requiem",          d: "explore", w: "solo",    s: "campaign",   f: "tension" },
        { n: "Heaven's Vault",                  d: "solve",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "The Walking Dead (Telltale)",     d: "solve",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Ico",                             d: "explore", w: "coop",    s: "campaign",   f: "tension" },
        { n: "Shadow of the Colossus",          d: "fight",   w: "solo",    s: "campaign",   f: "power" },
        { n: "The Last of Us Part I",           d: "fight",   w: "solo",    s: "campaign",   f: "tension" },
        { n: "Uncharted 4",                     d: "explore", w: "solo",    s: "campaign",   f: "power" },
        { n: "Death Stranding",                 d: "explore", w: "solo",    s: "persistent", f: "tension" },

        /* --- Roguelike and roguelite --- */
        { n: "Spelunky 2",                      d: "explore", w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Noita",                           d: "explore", w: "solo",    s: "runbased",   f: "tension" },
        { n: "Risk of Rain 2",                  d: "explore", w: "coop",    s: "runbased",   f: "power" },
        { n: "The Binding of Isaac: Rebirth",   d: "fight",   w: "solo",    s: "runbased",   f: "tension" },
        { n: "Enter the Gungeon",               d: "fight",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Rogue Legacy 2",                  d: "fight",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Gunfire Reborn",                  d: "fight",   w: "coop",    s: "runbased",   f: "power" },
        { n: "Streets of Rogue",                d: "fight",   w: "solo",    s: "runbased",   f: "power" },
        { n: "Curse of the Dead Gods",          d: "fight",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Skul: The Hero Slayer",           d: "fight",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Children of Morta",               d: "fight",   w: "coop",    s: "runbased",   f: "power" },
        { n: "Have a Nice Death",               d: "fight",   w: "solo",    s: "runbased",   f: "mastery" },
        { n: "20 Minutes Till Dawn",            d: "fight",   w: "solo",    s: "runbased",   f: "power" },
        { n: "Brotato",                         d: "fight",   w: "solo",    s: "runbased",   f: "power" },
        { n: "Nuclear Throne",                  d: "fight",   w: "solo",    s: "runbased",   f: "tension" },
        { n: "Cult of the Lamb",                d: "command", w: "solo",    s: "persistent", f: "cozy" },
        { n: "Monster Train",                   d: "command", w: "solo",    s: "runbased",   f: "mastery" },
        { n: "Cursed to Golf",                  d: "solve",   w: "solo",    s: "runbased",   f: "cozy" },

        /* --- Survival, crafting, extraction --- */
        { n: "Rust",                            d: "fight",   w: "versus",  s: "persistent", f: "tension" },
        { n: "DayZ",                            d: "fight",   w: "versus",  s: "persistent", f: "tension" },
        { n: "Albion Online",                   d: "fight",   w: "versus",  s: "persistent", f: "power" },
        { n: "The Forest",                      d: "explore", w: "coop",    s: "campaign",   f: "tension" },
        { n: "Sons of the Forest",              d: "explore", w: "coop",    s: "persistent", f: "tension" },
        { n: "Green Hell",                      d: "explore", w: "solo",    s: "persistent", f: "tension" },
        { n: "Grounded",                        d: "explore", w: "coop",    s: "persistent", f: "cozy" },
        { n: "7 Days to Die",                   d: "fight",   w: "coop",    s: "persistent", f: "tension" },
        { n: "Raft",                            d: "command", w: "coop",    s: "persistent", f: "cozy" },
        { n: "Icarus",                          d: "explore", w: "coop",    s: "runbased",   f: "tension" },
        { n: "Dark and Darker",                 d: "fight",   w: "versus",  s: "runbased",   f: "tension" },
        { n: "V Rising",                        d: "fight",   w: "solo",    s: "persistent", f: "power" },
        { n: "Core Keeper",                     d: "explore", w: "coop",    s: "persistent", f: "cozy" },
        { n: "Astroneer",                       d: "explore", w: "coop",    s: "persistent", f: "cozy" },
        { n: "The Long Dark",                   d: "explore", w: "solo",    s: "persistent", f: "tension" },
        { n: "Don't Starve",                    d: "command", w: "solo",    s: "runbased",   f: "tension" },
        { n: "State of Decay 2",                d: "fight",   w: "coop",    s: "persistent", f: "tension" },
        { n: "Project Zomboid",                 d: "explore", w: "solo",    s: "persistent", f: "tension" },

        /* --- Hole-filling pass: targeted real games for cells the breadth
           pass left empty. Versus+Campaign and Massive+Campaign are left
           deliberately empty across every verb: both are structural
           contradictions (a versus game is shaped as repeatable matches,
           not a finite campaign; a massive shared world is persistent by
           definition, not authored to end). --- */
        { n: "Days Gone",                       d: "fight",   w: "solo",    s: "persistent", f: "tension" },
        { n: "SUPERHOT",                        d: "fight",   w: "solo",    s: "match",      f: "mastery" },
        { n: "Resident Evil 5",                 d: "fight",   w: "coop",    s: "campaign",   f: "tension" },
        { n: "Warhammer: Vermintide 2",         d: "fight",   w: "coop",    s: "match",      f: "mastery" },
        { n: "Mordhau",                         d: "fight",   w: "versus",  s: "persistent", f: "mastery" },
        { n: "Chivalry 2",                      d: "fight",   w: "massive", s: "match",      f: "mastery" },
        { n: "Reigns",                          d: "command", w: "solo",    s: "match",      f: "power" },
        { n: "Islanders",                       d: "command", w: "solo",    s: "runbased",   f: "cozy" },
        { n: "Moving Out",                      d: "command", w: "coop",    s: "match",      f: "cozy" },
        { n: "Rise of Kingdoms",                d: "command", w: "versus",  s: "persistent", f: "power" },
        { n: "Iron Harvest",                    d: "command", w: "versus",  s: "match",      f: "tension" },
        { n: "Grand Theft Auto Online",         d: "explore", w: "versus",  s: "persistent", f: "power" },
        { n: "Lovers in Dangerous Spacetime",   d: "explore", w: "coop",    s: "runbased",   f: "mastery" },
        { n: "Cultist Simulator",               d: "solve",   w: "solo",    s: "persistent", f: "tension" },
        { n: "Luck be a Landlord",              d: "solve",   w: "solo",    s: "runbased",   f: "power" },
        { n: "Keep Talking Nobody Explodes",    d: "solve",   w: "coop",    s: "match",      f: "tension" }
      ]
    }
  }
};
